---
name: RSpec

env:
  BRIDGETOWN_VERSION: 1.0.0

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, head]
    runs-on: ubuntu-latest
    name: Test against Ruby ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: |
        bundle exec rake spec
